language: "en"
gui:
  title: "&8Editing: &b%shop% &8| Slot: &b%slot% &8| P: &b%page%"
  size: 54
  buy_adjustments:
    0: { material: "LIME_STAINED_GLASS_PANE", name: "&a+ 0.10", amount: 0.1 }
    1: { material: "LIME_DYE", name: "&a+ 1.00", amount: 1.0 }
    2: { material: "LIME_WOOL", name: "&a+ 10.00", amount: 10.0 }
    3: { material: "LIME_CONCRETE", name: "&a+ 100.00", amount: 100.0 }
    4: { material: "EMERALD", name: "&a+ 1,000.00", amount: 1000.0 }
    5: { material: "EMERALD_BLOCK", name: "&a+ 10,000.00", amount: 10000.0 }
    6: { material: "DIAMOND", name: "&a+ 100,000.00", amount: 100000.0 }
    7: { material: "NETHER_STAR", name: "&b&l+ 1,000,000.00", amount: 1000000.0 }
  sell_adjustments:
    0: { material: "RED_STAINED_GLASS_PANE", name: "&c+ 0.10", amount: 0.1 }
    1: { material: "RED_DYE", name: "&c+ 1.00", amount: 1.0 }
    2: { material: "RED_WOOL", name: "&c+ 10.00", amount: 10.0 }
    3: { material: "RED_CONCRETE", name: "&c+ 100.00", amount: 100.0 }
    4: { material: "REDSTONE", name: "&c+ 1,000.00", amount: 1000.0 }
    5: { material: "REDSTONE_BLOCK", name: "&c+ 10,000.00", amount: 10000.0 }
    6: { material: "TNT", name: "&c+ 100,000.00", amount: 100000.0 }
    7: { material: "NETHERITE_BLOCK", name: "&4&l+ 1,000,000.00", amount: 1000000.0 }
  controls:
    reload_sga: 
      material: "CLOCK"
      name: "&bReload ShopGuiAddon"
    reload_sgp: 
      material: "BLAZE_POWDER"
      name: "&6Reload ShopGUI+"
list_settings:
  header: "&b&lAvailable Shops in /shops:"
  prefix: " &7- &f"
