name: ShopGuiAddon
version: 1.1
main: com.comonier.shopguiaddon.ShopGuiAddon
api-version: '1.21'
author: Comonier
depend: [ShopGUIPlus]
description: Addon avançado para ShopGUI+ com suporte a Skins, Lore e Edição Visual.
commands:
  sga:
    description: Comando principal do ShopGuiAddon.
    usage: /sga [help|edit|itemadd|reload|shopcreate|link|replace|menu|item]
    permission: shopguiaddon.admin
