name: ShopGuiAddon
version: '1.4'
main: com.comonier.shopguiaddon.ShopGuiAddon
api-version: '1.21'
author: Comonier
description: Advanced ShopGUI+ addon with visual editing, skin support, quantity management, and menu management.
load: POSTWORLD

# O plugin só inicia após o ShopGUIPlus ser detectado
depend:
  - ShopGUIPlus

commands:
  sga:
    description: Comando principal do ShopGuiAddon.
    aliases: [shopguiaddon, sgaedit]
    usage: /sga [help|edit|itemadd|itemremove|reload|shopcreate|shopremove|link|replace|unlink|menu|item]
    permission: shopguiaddon.admin
    permission-message: "&cVocê não tem permissão para usar este comando!"

permissions:
  shopguiaddon.admin:
    description: Permite acesso total às funções de edição e gerenciamento do addon.
    default: op
